#!/bin/bash

PYTHON="$(which python3)"
PIP="$(which pip)"

if [[ -x "$PYTHON" ]] & [[ -x "$PIP" ]];
then
    $PIP install pymongo
    $PYTHON install.py "$@"
else
    echo  "Python 3 is required, exiting..."
fi
